CREATE TABLE PESSOA (
    ID INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TEL VARCHAR(20) 
);


CREATE TABLE PRODUTO (
    ID INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ESCRICAO TEXT,
    DATA_INC DATE NOT NULL,
    DATA_FIN DATE not null,
    STATUS VARCHAR(20)
);

CREATE TABLE PESSOA_PRODUTO (
    ID_PESSOA INT,
    ID_PRODUTO INT,
    PRIMARY KEY (ID_PESSOA, ID_PRODUTO),
    FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID) ON DELETE CASCADE
);